### PR TITLE
Initial merge

### PR DESCRIPTION
**Pull request by dmakfan**
Initial merge to bring coallesce the contents of arch/cm4f/topaz/gcc into a single repository.

### CODE REVIEW

**Comment by dmakfan** [comment]
@ShivaniFW the commit message is really just for the github.  It won't show up in the history because all of these changes are essentialy applying patches.

So the actual git history will not show any history of this migration happening.  If it woudl be helpful, we could always drop a label to indicate when it happened.

**Comment by dmalea** [comment]
Thanks for taking this on!

I think there's a few more repositories that need to be included in the Great Migration:
- stuff under the top-level `lib` such as `logger` (and `protocol`?)
- scripts under the top-level `build` such as `set_target.sh`, `build.sh` and `test.sh`
- the top-level Dockerfile

I guess we're changing the dir structure anyways, it might make sense to put those in as separate commits -- but are we OK with losing history from those repositories? I don't have any major concerns, if that was your intent; just wanted to make sure.

**Comment by dmalea** [comment]
It should likely be done in a separate commit (maybe even a separate PR) but build instructions should be added as well.

**Comment by dmakfan** [comment]
@dmalea For the ./lib changes, yeah, we have to do that in a separate commit, and likely after we fix the directory structure.  It's in the slack channel with us and Shivani, but basically, it has to do with the relative directories from root, and that there is already a repo project at root. 

Good point about updating the build instructions.  Let's do it on a separate commit though to keep this one as a coallescing PR that does not introduce any new changes at the same time.

**Comment by jimmyorourke** [comment]
I just wanted to point out that the way this was merged added a sort of gross merge commit. For transferring and committing many previous commits without squashing you may want to try rebase merging instead.

**Comment by dmalea** [comment]
Good point - while I think we want to avoid merge commits in the future, in this case it was intentional as we're switching trees from multiple gitlab repositories -> single github repository for Topaz things. We want to have some sort of marker to denote the instant that we did the switch.

**Pull request merged**
